spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/restful_api
    username: root
  servlet:
    multipart:
      max-file-size: 100KB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
settings:
  extension: jpeg,jpg,png,gif